[metadata]
name = "wordlist"
version = "1.1.0"
author = "matt wartell"
author-email = "matt.wartell@gmail.com"
home-page = "https://github.com/mwartell"
description = "create a list of words from various corpora"
long_description = "file: README.md"
long_description_content_type = "text/markdown"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
]


[options]
zip_safe = false
include_package_data = true
python_requires = ">= 3.6"
packages = ["wordlist"]
test_suite = "tests"

[options.extras_require]
dev = [
    "black",
    "pylint",
]
test = [
    "pytest",
]

[bdist_wheel]
universal = true

[flake8]
[mypy]
